//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTrackerData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketTrackerEntities2 : DbContext
    {
        public TicketTrackerEntities2()
            : base("name=TicketTrackerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Show> Shows { get; set; }
        public virtual DbSet<ShowPrice> ShowPrices { get; set; }
        public virtual DbSet<ShowType> ShowTypes { get; set; }
    }
}
